### PR TITLE
Upgrade nestjs ^8.0.0 and fireorm ^0.23.3

### PR DESCRIPTION
**Pull request by bramford**
A fresh NestJS project created by nest-cli depends on `^8.0.0`
Meanwhile the latest release version of fireorm is `0.23.3`

### CODE REVIEW

**Review by glebbash — CHANGES_REQUESTED** [review]
Hi, this shouldn't be locked to specific versions. I think "@nestjs/common": "8 || 9" and "fireorm": "> 0.20" will be better. Can you update your PR?

btw tests are also failing :)

**Comment by glebbash** [comment]
Or I can do that, if you prefer)

**Comment by bramford** [comment]
Change has been made. Feel free to kick off those workflows again.

**Comment by glebbash** [comment]
Tests were still failing so I upgraded the whole library using [create-ts-lib-gh](https://github.com/glebbash/create-ts-lib-gh).

Peer deps versions should be fixed in 1.1.0

**Pull request closed without merging**
